version: '3'
services:
 web:
  image: "node:12"
  labels:
    - "traefik.http.routers.api-crm.rule=Host(`${URL_PROXY_REVERSE}`)"
    - "traefik.http.services.api-crm.loadbalancer.server.port=3000"
    - "traefik.docker.network=traefik"
  user: "root"
  working_dir: /home/node/app
  volumes:
   - ./:/home/node/app
  ports:
   - 3000:3000
  command: "node app.js"
  networks: 
   - traefik

 traefik:
  image: "traefik:v2.0.1"
  command:
   - --entrypoints.web.address=:80
   - --providers.docker
   - --api.insecure
  ports:
   - "80:80"
   - "8080:8080"
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock:ro"
  networks: 
   - traefik

networks:
  traefik:
    external: true 